<a href="https://colab.research.google.com/github/Abishek-077/AI-l-ML---PROJECTS/blob/main/Numpy_Concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Basics


In [ ]:
import numpy as np

# 1D array
a = np.array([1, 2, 3])

# 2D array
b = np.array([[1, 2], [3, 4]])

# 3D array
c = np.array([[[1], [2]], [[3], [4]]])


2. Shape — .shape Attribute

In [ ]:
print(a.shape)  # (3,)     → 1D array with 3 elements
print(b.shape)  # (2, 2)   → 2 rows, 2 columns
print(c.shape)  # (2, 2, 1) → 3D array


(3,)
(2, 2)
(2, 2, 1)


3. Data Types — .dtype Attribute

In [ ]:
x = np.array([1,2,4])
print(x.dtype)

y = np.array([1.0,2.0,3.0])
print(y.dtype)

z = np.array(['a','b','c'])
print(z.dtype)

# We can type data explecitly
w = np.array([1,2,3],dtype='float32')

int64
float64
<U1


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
resize = arr.reshape(3,3)
print(resize)
reshaped = arr.reshape(3, -1)  # NumPy will figure out the number of columns (3 rows, automatically 2 columns)
print(reshaped)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


2. Transposing — transpose()

In [ ]:
arr_2d =np.array([[1,2,3],[4,5,6]])
transposed = arr_2d.transpose()
print(transposed.shape)
print (transposed)

(3, 2)
[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr_3d =np.array([[[1,2],[3,4],[5,6],[7,8]]])
transposed = arr_3d.transpose()
print(transposed.shape)
print (transposed)

(2, 4, 1)
[[[1]
  [3]
  [5]
  [7]]

 [[2]
  [4]
  [6]
  [8]]]


Flattening Targets for Traning

In [ ]:
y =np.array([[[1],[0],[1],[1],[0]]])
x = np.array([[[1,2],[3,4],[5,6],[7,8],[9,10]]])
print(x.shape)
print(y.shape)
y_flattened = y.flatten()
print(y_flattened)

x_flattened = x.flatten()
print(x_flattened)

(1, 5, 2)
(1, 5, 1)
[1 0 1 1 0]
[ 1  2  3  4  5  6  7  8  9 10]


This reshaping and flattening are essential for passing data into models that require specific input formats (e.g., scikit-learn models).

Summary:
Reshape (reshape()) to change the shape of the array.

Transpose (transpose()) to swap rows and columns (or more complex rearrangements for higher-dimensional arrays).

Ravel (ravel()) to flatten the array into 1D.

5. Aggregation Functions	sum(), mean(), std(), argmax()	Feature engineering, analysis

---



In [ ]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(a))           # Sum of all elements → 21
print(np.sum(a, axis=0))   # Column-wise sum → [5 7 9]
print(np.sum(a, axis=1))   # Row-wise sum → [6 15]


21
[5 7 9]
[ 6 15]


mean() - Average of elements

In [ ]:
print(np.mean(a))
print(np.mean(a,axis=0))

3.5
[2.5 3.5 4.5]


std() — Standard Deviation

In [ ]:
print(np.std(a))
# help us find the dominatnt features
print(np.argmax(a))

1.707825127659933
5


Quick Example of Normalizing the data

In [ ]:
data = np.array([10,11,12,13,14,15])
mean = np.mean(data)
std= np.std(data)

noramlization =(data-mean)/std
print(noramlization)
# we do it compress the the learning

[-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


Logical Operation And filtering in Numpy


In [ ]:
import numpy as np

arr = np.array([1, 6, 8, 3, 2])

# Logical condition
mask = arr > 5  # [False, True, True, False, False]
filtered = arr[mask]  # [6, 8]

# np.where() - Gives indices where condition is True
indices = np.where(arr > 5)  # (array([1, 2]),)

# any() and all()
print(np.any(arr > 5))  # True (at least one element > 5)
print(np.all(arr > 5))  # False (not all elements > 5)


True
False


Random Module In NumPy

In [ ]:
np.random.rand(3); # folat number bet

np.random.randn

2. What is Vectorization ?
Vectorization means applying an operation on the whole array at once using optimized C under the hood (via NumPy).

In [ ]:
squares_vec = arr**2

Performance Comparision

In [ ]:
import time

arr = np.arange(1_000_000)

# For-loop timing
start = time.time()
squares = [i**2 for i in arr]
print("For-loop time:", time.time() - start)

# Vectorized timing
start = time.time()
squares_vec = arr ** 2
print("Vectorized time:", time.time() - start)


For-loop time: 0.14803719520568848
Vectorized time: 0.012206315994262695
